[versions]
agp = "8.9.0"
yahfa = "0.10.0"

[libraries]
yahfa = { module = "io.github.pagalaxylab:yahfa", version.ref = "yahfa" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

